name: CI - DemoBlaze Automation Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          chromium-browser \
          chromium-chromedriver \
          firefox \
          xvfb
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/requirements.txt
    
    - name: Create directories
      run: |
        mkdir -p automation/reports
        mkdir -p automation/screenshots
        mkdir -p automation/logs
    
    - name: Run tests with pytest
      env:
        BROWSER: ${{ matrix.browser }}
        HEADLESS: true
        BASE_URL: https://www.demoblaze.com/
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        pytest automation/tests/ \
          --html=automation/reports/report.html \
          --self-contained-html \
          --junitxml=automation/reports/junit.xml \
          -v
    
    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report-${{ matrix.browser }}
        path: automation/reports/report.html
        retention-days: 30
    
    - name: Upload JUnit XML
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: junit-xml-${{ matrix.browser }}
        path: automation/reports/junit.xml
        retention-days: 30
    
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: screenshots-${{ matrix.browser }}
        path: automation/screenshots/
        retention-days: 7
    
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: logs-${{ matrix.browser }}
        path: automation/logs/
        retention-days: 7

